### ISSUE TITLE
[Question] Will there be a pre-built version?

### ISSUE THREAD

**Issue by sonicdemo** [itsmattkc/RunnersDecomp#1]
Will there be an pre-built version in the Releases tab for Windows? Having to pay to build isn't worth it for me. (You would need to obtain the assets from the android version still.)

**Comment by itsmattkc** [comment]
There is currently no plan to provide builds from this repo. Builds with extra enhancements and bug fixes are provided by the [Revival project](https://sonicrunners.com/), and I believe they do plan to make a Windows port available at some point.

**Comment by sonicdemo** [comment]
> There is currently no plan to provide builds from this repo. Builds with extra enhancements and bug fixes are provided by the [Revival project](https://sonicrunners.com/), and I believe they do plan to make a Windows port available at some point.

"A: We do not have any current plans to bring Runners to PC at this time." I don't know.

**Comment by sonicdemo** [comment]
Maybe just post it not in the releases tab or somewhere else, i have no idea

**Comment by F121Live** [comment]
Revival will eventually have a PC build, we just want to make proper configurations, and fix issues related to framerate first.
