### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by sonicdemo** [itsmattkc/RunnersDecomp#2]
![Zrzut ekranu (2503)](https://user-images.githubusercontent.com/121387979/234972215-17168530-6766-4a84-a978-abbb20edab51.png)
![Zrzut ekranu (2504)](https://user-images.githubusercontent.com/121387979/234972222-e3b930df-f34e-4584-bfac-5fc38643ea72.png)
Got these "The namespace `global::` already contains a definition for..." some objects and a warning, help 🙏

**Comment by sonicdemo** [comment]
I think i'd better ask in the Revival discord

**Comment by sonicdemo** [comment]
Oh, i don't think i can, reopening💀

**Comment by sonicdemo** [comment]
Now got 74 errors after trying to fix it myself, i give up

**Comment by F121Live** [comment]
This means that you have a duplicate of NGUI on your project directory... Maybe try again with a fresh clone of the repo?
