### ISSUE TITLE
Compiling on MacOS?

### ISSUE THREAD

**Issue by AwayCoast23465** [itsmattkc/RunnersDecomp#3]
I wanted to try the decomp out on my m1 mac, but it vaguely says that it is straight forward. I cant even find unity 4.6.9 for mac. can anyone help?

**Comment by itsmattkc** [comment]
http://beta.unity3d.com/download/unity-4.6.9.dmg

**Comment by AwayCoast23465** [comment]
thank you, but apparently this version is 32 bit so i cant use it. is there any other alternatives?

**Comment by itsmattkc** [comment]
I'm afraid not, that's just the reality of working with old software on macOS. The Runners client team has been working on making an upgraded version of the project for newer versions of Unity, but it's not finished yet.

**Comment by itsmattkc** [comment]
There is actually a potential workaround. You should be able to use CrossOver to run the Windows version of Unity 4.6.9 on macOS. It won't feel quite as nice as the native version, but it should work properly. CrossOver handles the conversion from 32 to 64-bit, as well as from x86 to ARM (M1).

Alternatively you can use a virtual machine like Parallels to run Windows itself, which will provide more compatibility/accuracy at the expense of lower performance.
